[versions]
coroutines = "1.6.4"
junit = "5.9.2"
kotlin = "1.8.10"
mockk = "1.13.3"
detekt = "1.22.0"
dokka = "1.7.20"
spotless = "6.9.1"
dependency = "1.18.0"
pitest = "1.9.0"
ktlint = "0.48.1"
assertj = "3.24.1"

[libraries]
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
detekt_formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kt-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kt-serializatin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency" }
pitest = { id = "info.solidsoft.pitest", version.ref = "pitest" }
